/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package jframes;

import java.awt.Color;
import java.util.Date;
import java.sql.SQLException;
import java.text.SimpleDateFormat;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;
import software.advanced_software_project.Guest;
import software.advanced_software_project.Reservation;
import software.advanced_software_project.Room;
import software.advanced_software_project.User;

/**
 *
 * @author ALAMIA
 */
public class Home extends javax.swing.JFrame {

    private final String url = "jdbc:mysql://localhost:3306/software_project";

    /**
     * Creates new form Home
     */
    public Home() {
        initComponents();
        Guest.update_guests_table(url, table_guest);
        Room.update_rooms_table(url, table_room);
        Reservation.update_reservation_table(url, table_reservation);
        User.update_users_table(url, table_user);
        try {
            Reservation.getGuests(url, combo_guest_id);
            Reservation.getRooms(url, combo_room_id);

        } catch (SQLException ex) {
            Logger.getLogger(Home.class.getName()).log(Level.SEVERE, null, ex);
        }
        Guest.count_nums(url, label_numGuests);
        Room.count_free_rooms(url, label_free);
        Room.count_booked_rooms(url, label_booked);
        Reservation.count_total_income(url, label_income);

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnGroup_Guest = new javax.swing.ButtonGroup();
        btnGroup_Room = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        reservations = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        rooms = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        dashboard = new javax.swing.JPanel();
        label_dashboard = new javax.swing.JLabel();
        guests = new javax.swing.JPanel();
        jLabel14 = new javax.swing.JLabel();
        manage_users = new javax.swing.JPanel();
        jLabel33 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        btn_logout = new rojeru_san.complementos.RSButtonHover();
        jLabel2 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        tab_dashboard = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel23 = new javax.swing.JLabel();
        label_numGuests = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        jLabel25 = new javax.swing.JLabel();
        label_booked = new javax.swing.JLabel();
        jPanel5 = new javax.swing.JPanel();
        jLabel27 = new javax.swing.JLabel();
        label_free = new javax.swing.JLabel();
        jLabel29 = new javax.swing.JLabel();
        jLabel30 = new javax.swing.JLabel();
        jLabel31 = new javax.swing.JLabel();
        jLabel32 = new javax.swing.JLabel();
        jPanel6 = new javax.swing.JPanel();
        jLabel24 = new javax.swing.JLabel();
        label_income = new javax.swing.JLabel();
        tab_guests = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        table_guest = new rojeru_san.complementos.RSTableMetro();
        jPanel7 = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        txt_city = new app.bolivia.swing.JCTextField();
        txt_email = new app.bolivia.swing.JCTextField();
        txt_phone = new app.bolivia.swing.JCTextField();
        txt_name = new app.bolivia.swing.JCTextField();
        jLabel12 = new javax.swing.JLabel();
        btn_insert_guest = new rojeru_san.complementos.RSButtonHover();
        btn_update_guest = new rojeru_san.complementos.RSButtonHover();
        jLabel16 = new javax.swing.JLabel();
        radio_female = new javax.swing.JRadioButton();
        radio_male = new javax.swing.JRadioButton();
        btn_remove_guest = new rojeru_san.complementos.RSButtonHover();
        combo_search_guest = new rojerusan.RSComboMetro();
        txt_search_guest = new javax.swing.JTextField();
        btn_clear_guest = new rojeru_san.complementos.RSButtonHover();
        jLabel9 = new javax.swing.JLabel();
        tab_rooms = new javax.swing.JPanel();
        jPanel8 = new javax.swing.JPanel();
        jLabel15 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        txt_price = new app.bolivia.swing.JCTextField();
        txt_room_number = new app.bolivia.swing.JCTextField();
        jLabel20 = new javax.swing.JLabel();
        btn_insert_room = new rojeru_san.complementos.RSButtonHover();
        btn_update_room = new rojeru_san.complementos.RSButtonHover();
        jLabel21 = new javax.swing.JLabel();
        radio_booked = new javax.swing.JRadioButton();
        radio_free = new javax.swing.JRadioButton();
        btn_remove_room = new rojeru_san.complementos.RSButtonHover();
        combo_search_status = new rojerusan.RSComboMetro();
        btn_refresh = new rojeru_san.complementos.RSButtonHover();
        jLabel22 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        table_room = new rojeru_san.complementos.RSTableMetro();
        combo_room_type = new javax.swing.JComboBox<>();
        combo_bedrooms = new javax.swing.JComboBox<>();
        combo_search_type = new rojerusan.RSComboMetro();
        btn_clear3 = new rojeru_san.complementos.RSButtonHover();
        tab_reservations = new javax.swing.JPanel();
        jPanel9 = new javax.swing.JPanel();
        jLabel36 = new javax.swing.JLabel();
        jLabel37 = new javax.swing.JLabel();
        txt_cost = new app.bolivia.swing.JCTextField();
        jLabel38 = new javax.swing.JLabel();
        btn_insert_rsv = new rojeru_san.complementos.RSButtonHover();
        jLabel39 = new javax.swing.JLabel();
        btn_remove_rsv = new rojeru_san.complementos.RSButtonHover();
        combo_search_reservation = new rojerusan.RSComboMetro();
        txt_search_reservation = new javax.swing.JTextField();
        jLabel40 = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        table_reservation = new rojeru_san.complementos.RSTableMetro();
        combo_room_id = new javax.swing.JComboBox<>();
        combo_guest_id = new javax.swing.JComboBox<>();
        jLabel41 = new javax.swing.JLabel();
        jLabel42 = new javax.swing.JLabel();
        btn_get_cost = new javax.swing.JButton();
        date_check_out = new rojeru_san.componentes.RSDateChooser();
        date_check_in = new rojeru_san.componentes.RSDateChooser();
        tab_manage_users = new javax.swing.JPanel();
        jPanel10 = new javax.swing.JPanel();
        jLabel35 = new javax.swing.JLabel();
        jLabel43 = new javax.swing.JLabel();
        jLabel44 = new javax.swing.JLabel();
        txt_user_phone = new app.bolivia.swing.JCTextField();
        txt_user_email = new app.bolivia.swing.JCTextField();
        txt_user_password = new app.bolivia.swing.JCTextField();
        txt_username = new app.bolivia.swing.JCTextField();
        jLabel45 = new javax.swing.JLabel();
        btn_insert_user = new rojeru_san.complementos.RSButtonHover();
        btn_update_user = new rojeru_san.complementos.RSButtonHover();
        jLabel46 = new javax.swing.JLabel();
        btn_remove_user = new rojeru_san.complementos.RSButtonHover();
        combo_search_user = new rojerusan.RSComboMetro();
        txt_search_user = new javax.swing.JTextField();
        btn_clear_user = new rojeru_san.complementos.RSButtonHover();
        jLabel47 = new javax.swing.JLabel();
        jScrollPane4 = new javax.swing.JScrollPane();
        table_user = new rojeru_san.complementos.RSTableMetro();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(255, 255, 255));
        setMinimumSize(new java.awt.Dimension(1100, 650));
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(0, 153, 153));
        jPanel1.setPreferredSize(new java.awt.Dimension(280, 650));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        reservations.setBackground(new java.awt.Color(0, 153, 153));
        reservations.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(255, 255, 255)));
        reservations.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel5.setFont(new java.awt.Font("Tempus Sans ITC", 1, 24)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setIcon(new javax.swing.ImageIcon("C:\\Users\\ALAMIA\\Desktop\\Software Project\\Library Management System icons-20240416T231307Z-001\\Library Management System icons\\icons\\booking.png")); // NOI18N
        jLabel5.setText(" Reservations");
        jLabel5.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel5.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel5MouseClicked(evt);
            }
        });
        reservations.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 0, 260, 60));

        jPanel1.add(reservations, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 290, 280, 60));

        rooms.setBackground(new java.awt.Color(0, 153, 153));
        rooms.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(255, 255, 255)));
        rooms.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel4.setFont(new java.awt.Font("Tempus Sans ITC", 1, 24)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setIcon(new javax.swing.ImageIcon("C:\\Users\\ALAMIA\\Desktop\\Software Project\\Library Management System icons-20240416T231307Z-001\\Library Management System icons\\icons\\room.png")); // NOI18N
        jLabel4.setText(" Rooms");
        jLabel4.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel4MouseClicked(evt);
            }
        });
        rooms.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 0, 260, 60));

        jPanel1.add(rooms, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 230, 280, 60));

        dashboard.setBackground(new java.awt.Color(0, 102, 102));
        dashboard.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(255, 255, 255)));
        dashboard.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        label_dashboard.setFont(new java.awt.Font("Tempus Sans ITC", 1, 24)); // NOI18N
        label_dashboard.setForeground(new java.awt.Color(255, 255, 255));
        label_dashboard.setIcon(new javax.swing.ImageIcon("C:\\Users\\ALAMIA\\Desktop\\Software Project\\Library Management System icons-20240416T231307Z-001\\Library Management System icons\\icons\\dashboard.png")); // NOI18N
        label_dashboard.setText(" Dashboard");
        label_dashboard.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        label_dashboard.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                label_dashboardMouseClicked(evt);
            }
        });
        dashboard.add(label_dashboard, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 0, 260, 60));

        jPanel1.add(dashboard, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 110, 280, 60));

        guests.setBackground(new java.awt.Color(0, 153, 153));
        guests.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(255, 255, 255)));
        guests.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel14.setFont(new java.awt.Font("Tempus Sans ITC", 1, 24)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(255, 255, 255));
        jLabel14.setIcon(new javax.swing.ImageIcon("C:\\Users\\ALAMIA\\Desktop\\Software Project\\Library Management System icons-20240416T231307Z-001\\Library Management System icons\\icons\\tourist.png")); // NOI18N
        jLabel14.setText("Guests");
        jLabel14.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel14.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel14MouseClicked(evt);
            }
        });
        guests.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 0, 260, 60));

        jPanel1.add(guests, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 170, 280, 60));

        manage_users.setBackground(new java.awt.Color(0, 153, 153));
        manage_users.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(255, 255, 255)));
        manage_users.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel33.setFont(new java.awt.Font("Tempus Sans ITC", 1, 24)); // NOI18N
        jLabel33.setForeground(new java.awt.Color(255, 255, 255));
        jLabel33.setIcon(new javax.swing.ImageIcon("C:\\Users\\ALAMIA\\Desktop\\Software Project\\businessman.png")); // NOI18N
        jLabel33.setText(" Manage Users");
        jLabel33.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel33.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel33MouseClicked(evt);
            }
        });
        manage_users.add(jLabel33, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 0, 260, 60));

        jPanel1.add(manage_users, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 350, 280, 60));

        jLabel3.setIcon(new javax.swing.ImageIcon("C:\\Users\\ALAMIA\\Desktop\\Software Project\\Library Management System icons-20240416T231307Z-001\\Library Management System icons\\icons\\check-out.png")); // NOI18N
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 560, -1, -1));

        btn_logout.setBackground(new java.awt.Color(0, 153, 153));
        btn_logout.setText("LogOut");
        btn_logout.setColorHover(new java.awt.Color(255, 51, 102));
        btn_logout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_logoutActionPerformed(evt);
            }
        });
        jPanel1.add(btn_logout, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 550, 280, 50));

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setIcon(new javax.swing.ImageIcon("C:\\Users\\ALAMIA\\Desktop\\Software Project\\Library Management System icons-20240416T231307Z-001\\Library Management System icons\\adminIcons\\icons8_Home_26px_2.png")); // NOI18N
        jLabel2.setText("  Home page");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 0, 180, 50));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 50, 280, 600));

        jPanel3.setBackground(new java.awt.Color(0, 153, 153));
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setIcon(new javax.swing.ImageIcon("C:\\Users\\ALAMIA\\Desktop\\Software Project\\Library Management System icons-20240416T231307Z-001\\Library Management System icons\\adminIcons\\icons8_menu_48px_1.png")); // NOI18N
        jPanel3.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 0, -1, -1));

        jLabel13.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(255, 0, 0));
        jLabel13.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel13.setIcon(new javax.swing.ImageIcon("C:\\Users\\ALAMIA\\Desktop\\Software Project\\Library Management System icons-20240416T231307Z-001\\Library Management System icons\\icons\\delete.png")); // NOI18N
        jLabel13.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel13.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel13MouseClicked(evt);
            }
        });
        jPanel3.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(1040, 10, 50, 40));

        jLabel6.setFont(new java.awt.Font("Tw Cen MT", 1, 36)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Hotel Management System");
        jPanel3.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 0, 490, 50));

        getContentPane().add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1100, 50));

        tab_dashboard.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBackground(new java.awt.Color(204, 204, 204));
        jPanel2.setBorder(javax.swing.BorderFactory.createMatteBorder(6, 0, 0, 0, new java.awt.Color(0, 153, 153)));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel23.setIcon(new javax.swing.ImageIcon("C:\\Users\\ALAMIA\\Desktop\\Software Project\\guests.png")); // NOI18N
        jPanel2.add(jLabel23, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 30, -1, -1));

        label_numGuests.setFont(new java.awt.Font("Segoe UI Black", 0, 50)); // NOI18N
        label_numGuests.setText("6");
        jPanel2.add(label_numGuests, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 40, 120, 50));

        tab_dashboard.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 100, 300, 130));

        jPanel4.setBackground(new java.awt.Color(204, 204, 204));
        jPanel4.setBorder(javax.swing.BorderFactory.createMatteBorder(6, 0, 0, 0, new java.awt.Color(204, 0, 0)));
        jPanel4.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel25.setIcon(new javax.swing.ImageIcon("C:\\Users\\ALAMIA\\Desktop\\Software Project\\booked-room.png")); // NOI18N
        jPanel4.add(jLabel25, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 30, -1, -1));

        label_booked.setFont(new java.awt.Font("Segoe UI Black", 0, 50)); // NOI18N
        label_booked.setText("6");
        jPanel4.add(label_booked, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 40, 120, 50));

        tab_dashboard.add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 100, 300, 130));

        jPanel5.setBackground(new java.awt.Color(204, 204, 204));
        jPanel5.setBorder(javax.swing.BorderFactory.createMatteBorder(6, 0, 0, 0, new java.awt.Color(204, 0, 0)));
        jPanel5.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel27.setIcon(new javax.swing.ImageIcon("C:\\Users\\ALAMIA\\Desktop\\Software Project\\free-room.png")); // NOI18N
        jPanel5.add(jLabel27, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 30, -1, -1));

        label_free.setFont(new java.awt.Font("Segoe UI Black", 0, 50)); // NOI18N
        label_free.setText("6");
        jPanel5.add(label_free, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 40, 130, 50));

        tab_dashboard.add(jPanel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 350, 300, 130));

        jLabel29.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel29.setText("Free Rooms");
        tab_dashboard.add(jLabel29, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 320, 180, -1));

        jLabel30.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel30.setText("No of Guests");
        tab_dashboard.add(jLabel30, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 70, 180, -1));

        jLabel31.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel31.setText("Booked Rooms");
        tab_dashboard.add(jLabel31, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 70, 180, -1));

        jLabel32.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel32.setText("Daily Income");
        tab_dashboard.add(jLabel32, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 320, 180, -1));

        jPanel6.setBackground(new java.awt.Color(204, 204, 204));
        jPanel6.setBorder(javax.swing.BorderFactory.createMatteBorder(6, 0, 0, 0, new java.awt.Color(0, 153, 153)));
        jPanel6.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel24.setIcon(new javax.swing.ImageIcon("C:\\Users\\ALAMIA\\Desktop\\Software Project\\cash.png")); // NOI18N
        jPanel6.add(jLabel24, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 30, -1, -1));

        label_income.setFont(new java.awt.Font("Segoe UI Black", 0, 50)); // NOI18N
        label_income.setText("800$");
        jPanel6.add(label_income, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 40, 220, 50));

        tab_dashboard.add(jPanel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 350, 300, 130));

        jTabbedPane1.addTab("dashboard", tab_dashboard);

        tab_guests.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        table_guest.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "Guest Id", "Name", "Phone", "Email", "City", "Gender"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        table_guest.setColorBackgoundHead(new java.awt.Color(0, 153, 153));
        table_guest.setColorSelBackgound(new java.awt.Color(255, 51, 102));
        table_guest.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        table_guest.setRowHeight(30);
        table_guest.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                table_guestMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(table_guest);

        tab_guests.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 330, 790, 270));

        jPanel7.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel7.setFont(new java.awt.Font("Segoe UI Semibold", 0, 14)); // NOI18N
        jLabel7.setText("Gender");
        jPanel7.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 230, 100, 40));

        jLabel8.setFont(new java.awt.Font("Segoe UI Semibold", 0, 14)); // NOI18N
        jLabel8.setText("Name");
        jPanel7.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 40, 100, 30));

        jLabel10.setFont(new java.awt.Font("Segoe UI Semibold", 0, 14)); // NOI18N
        jLabel10.setText("Email Address");
        jPanel7.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 130, 100, 50));

        jLabel11.setFont(new java.awt.Font("Segoe UI Semibold", 0, 14)); // NOI18N
        jLabel11.setText("Phone Number");
        jPanel7.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 90, 100, 40));
        jPanel7.add(txt_city, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 190, -1, -1));
        jPanel7.add(txt_email, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 140, -1, -1));
        jPanel7.add(txt_phone, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 90, -1, -1));
        jPanel7.add(txt_name, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 40, -1, -1));

        jLabel12.setIcon(new javax.swing.ImageIcon("C:\\Users\\ALAMIA\\Desktop\\Software Project\\Library Management System icons-20240416T231307Z-001\\Library Management System icons\\icons\\guest-list.png")); // NOI18N
        jPanel7.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 40, -1, -1));

        btn_insert_guest.setBackground(new java.awt.Color(0, 153, 153));
        btn_insert_guest.setText("Add");
        btn_insert_guest.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_insert_guestActionPerformed(evt);
            }
        });
        jPanel7.add(btn_insert_guest, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 40, -1, -1));

        btn_update_guest.setBackground(new java.awt.Color(0, 153, 153));
        btn_update_guest.setText("Update");
        btn_update_guest.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_update_guestActionPerformed(evt);
            }
        });
        jPanel7.add(btn_update_guest, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 110, -1, -1));

        jLabel16.setFont(new java.awt.Font("Segoe UI Semibold", 0, 14)); // NOI18N
        jLabel16.setText("City");
        jPanel7.add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 180, 100, 40));

        btnGroup_Guest.add(radio_female);
        radio_female.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        radio_female.setText("Female");
        jPanel7.add(radio_female, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 240, -1, -1));

        btnGroup_Guest.add(radio_male);
        radio_male.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        radio_male.setText("Male");
        jPanel7.add(radio_male, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 240, -1, -1));

        btn_remove_guest.setBackground(new java.awt.Color(0, 153, 153));
        btn_remove_guest.setText("Remove");
        btn_remove_guest.setColorHover(new java.awt.Color(255, 0, 0));
        btn_remove_guest.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_remove_guestActionPerformed(evt);
            }
        });
        jPanel7.add(btn_remove_guest, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 180, -1, -1));

        combo_search_guest.setBackground(new java.awt.Color(204, 204, 204));
        combo_search_guest.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "ID", "Name" }));
        combo_search_guest.setColorArrow(new java.awt.Color(0, 153, 153));
        combo_search_guest.setColorBorde(new java.awt.Color(0, 153, 153));
        combo_search_guest.setColorFondo(new java.awt.Color(0, 153, 153));
        combo_search_guest.setFont(new java.awt.Font("Serif", 0, 18)); // NOI18N
        combo_search_guest.setName("select"); // NOI18N
        jPanel7.add(combo_search_guest, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 280, 100, 30));

        txt_search_guest.setFont(new java.awt.Font("Serif", 0, 14)); // NOI18N
        txt_search_guest.setSelectionColor(new java.awt.Color(0, 153, 153));
        txt_search_guest.addCaretListener(new javax.swing.event.CaretListener() {
            public void caretUpdate(javax.swing.event.CaretEvent evt) {
                txt_search_guestCaretUpdate(evt);
            }
        });
        jPanel7.add(txt_search_guest, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 280, 310, 30));

        btn_clear_guest.setBackground(new java.awt.Color(0, 153, 153));
        btn_clear_guest.setText("Clear");
        btn_clear_guest.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_clear_guestActionPerformed(evt);
            }
        });
        jPanel7.add(btn_clear_guest, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 180, -1, -1));

        jLabel9.setFont(new java.awt.Font("Segoe UI Semibold", 0, 14)); // NOI18N
        jLabel9.setText("Search By");
        jPanel7.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 280, 140, 30));

        tab_guests.add(jPanel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 10, 820, 610));

        jTabbedPane1.addTab("guests", tab_guests);

        tab_rooms.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel8.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel15.setFont(new java.awt.Font("Segoe UI Semibold", 0, 14)); // NOI18N
        jLabel15.setText("Status");
        jPanel8.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 230, 100, 40));

        jLabel17.setFont(new java.awt.Font("Segoe UI Semibold", 0, 14)); // NOI18N
        jLabel17.setText("Room No");
        jPanel8.add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 40, 100, 30));

        jLabel18.setFont(new java.awt.Font("Segoe UI Semibold", 0, 14)); // NOI18N
        jLabel18.setText("Room Type");
        jPanel8.add(jLabel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 130, 120, 40));

        jLabel19.setFont(new java.awt.Font("Segoe UI Semibold", 0, 14)); // NOI18N
        jLabel19.setText("No of Bedrooms");
        jPanel8.add(jLabel19, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 80, 130, 40));
        jPanel8.add(txt_price, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 190, -1, -1));
        jPanel8.add(txt_room_number, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 40, -1, -1));

        jLabel20.setIcon(new javax.swing.ImageIcon("C:\\Users\\ALAMIA\\Desktop\\Software Project\\room.png")); // NOI18N
        jPanel8.add(jLabel20, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 40, -1, -1));

        btn_insert_room.setBackground(new java.awt.Color(0, 153, 153));
        btn_insert_room.setText("Add");
        btn_insert_room.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_insert_roomActionPerformed(evt);
            }
        });
        jPanel8.add(btn_insert_room, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 40, -1, -1));

        btn_update_room.setBackground(new java.awt.Color(0, 153, 153));
        btn_update_room.setText("Update");
        btn_update_room.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_update_roomActionPerformed(evt);
            }
        });
        jPanel8.add(btn_update_room, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 110, -1, -1));

        jLabel21.setFont(new java.awt.Font("Segoe UI Semibold", 0, 14)); // NOI18N
        jLabel21.setText("Price (per day)");
        jPanel8.add(jLabel21, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 180, 100, 40));

        btnGroup_Room.add(radio_booked);
        radio_booked.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        radio_booked.setText("Booked");
        jPanel8.add(radio_booked, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 240, -1, -1));

        btnGroup_Room.add(radio_free);
        radio_free.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        radio_free.setText("Free");
        jPanel8.add(radio_free, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 240, -1, -1));

        btn_remove_room.setBackground(new java.awt.Color(0, 153, 153));
        btn_remove_room.setText("Remove");
        btn_remove_room.setColorHover(new java.awt.Color(255, 0, 0));
        btn_remove_room.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_remove_roomActionPerformed(evt);
            }
        });
        jPanel8.add(btn_remove_room, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 180, -1, -1));

        combo_search_status.setBackground(new java.awt.Color(204, 204, 204));
        combo_search_status.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Free", "Booked" }));
        combo_search_status.setSelectedIndex(-1);
        combo_search_status.setColorArrow(new java.awt.Color(0, 153, 153));
        combo_search_status.setColorBorde(new java.awt.Color(0, 153, 153));
        combo_search_status.setColorFondo(new java.awt.Color(0, 153, 153));
        combo_search_status.setFont(new java.awt.Font("Serif", 0, 18)); // NOI18N
        combo_search_status.setName("select"); // NOI18N
        combo_search_status.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                combo_search_statusItemStateChanged(evt);
            }
        });
        jPanel8.add(combo_search_status, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 280, 130, 30));

        btn_refresh.setBackground(new java.awt.Color(0, 153, 153));
        btn_refresh.setText("Refresh");
        btn_refresh.setColorHover(new java.awt.Color(204, 204, 0));
        btn_refresh.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_refreshActionPerformed(evt);
            }
        });
        jPanel8.add(btn_refresh, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 280, 150, 30));

        jLabel22.setFont(new java.awt.Font("Segoe UI Semibold", 0, 14)); // NOI18N
        jLabel22.setText("Search By");
        jPanel8.add(jLabel22, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 280, 140, 30));

        table_room.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "Room Id", "Room No", "Bedrooms", "Room Type", "Status", "Price"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        table_room.setColorBackgoundHead(new java.awt.Color(0, 153, 153));
        table_room.setColorSelBackgound(new java.awt.Color(255, 51, 102));
        table_room.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        table_room.setRowHeight(30);
        table_room.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                table_roomMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(table_room);

        jPanel8.add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 330, 790, 270));

        combo_room_type.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Single", "Double", "VIB", "Suite", "Family" }));
        jPanel8.add(combo_room_type, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 140, 200, 30));

        combo_bedrooms.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "2", "3", "4", "5", "6" }));
        jPanel8.add(combo_bedrooms, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 90, 200, 30));

        combo_search_type.setBackground(new java.awt.Color(204, 204, 204));
        combo_search_type.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Single", "Double", "VIB", "Suite", "Family" }));
        combo_search_type.setSelectedIndex(-1);
        combo_search_type.setColorArrow(new java.awt.Color(0, 153, 153));
        combo_search_type.setColorBorde(new java.awt.Color(0, 153, 153));
        combo_search_type.setColorFondo(new java.awt.Color(0, 153, 153));
        combo_search_type.setFont(new java.awt.Font("Serif", 0, 18)); // NOI18N
        combo_search_type.setName("select"); // NOI18N
        combo_search_type.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                combo_search_typeItemStateChanged(evt);
            }
        });
        jPanel8.add(combo_search_type, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 280, 130, 30));

        btn_clear3.setBackground(new java.awt.Color(0, 153, 153));
        btn_clear3.setText("Clear");
        btn_clear3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_clear3ActionPerformed(evt);
            }
        });
        jPanel8.add(btn_clear3, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 180, -1, -1));

        tab_rooms.add(jPanel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 10, 820, 610));

        jTabbedPane1.addTab("rooms", tab_rooms);

        tab_reservations.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel9.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel36.setFont(new java.awt.Font("Segoe UI Semibold", 0, 14)); // NOI18N
        jLabel36.setText("Room id");
        jPanel9.add(jLabel36, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 90, 120, 40));

        jLabel37.setFont(new java.awt.Font("Segoe UI Semibold", 0, 14)); // NOI18N
        jLabel37.setText("Guest Id");
        jPanel9.add(jLabel37, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 40, 130, 40));

        txt_cost.setFocusable(false);
        jPanel9.add(txt_cost, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 160, 100, -1));

        jLabel38.setIcon(new javax.swing.ImageIcon("C:\\Users\\ALAMIA\\Desktop\\Software Project\\reserved.png")); // NOI18N
        jPanel9.add(jLabel38, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 30, -1, -1));

        btn_insert_rsv.setBackground(new java.awt.Color(0, 153, 153));
        btn_insert_rsv.setText("Add");
        btn_insert_rsv.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_insert_rsvActionPerformed(evt);
            }
        });
        jPanel9.add(btn_insert_rsv, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 190, -1, -1));

        jLabel39.setFont(new java.awt.Font("Segoe UI Semibold", 0, 14)); // NOI18N
        jLabel39.setText("Check out");
        jPanel9.add(jLabel39, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 270, 100, 40));

        btn_remove_rsv.setBackground(new java.awt.Color(0, 153, 153));
        btn_remove_rsv.setText("Remove");
        btn_remove_rsv.setColorHover(new java.awt.Color(255, 0, 0));
        btn_remove_rsv.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_remove_rsvActionPerformed(evt);
            }
        });
        jPanel9.add(btn_remove_rsv, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 190, -1, -1));

        combo_search_reservation.setBackground(new java.awt.Color(204, 204, 204));
        combo_search_reservation.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Guest ID", "Room ID" }));
        combo_search_reservation.setColorArrow(new java.awt.Color(0, 153, 153));
        combo_search_reservation.setColorBorde(new java.awt.Color(0, 153, 153));
        combo_search_reservation.setColorFondo(new java.awt.Color(0, 153, 153));
        combo_search_reservation.setFont(new java.awt.Font("Serif", 0, 18)); // NOI18N
        combo_search_reservation.setName("select"); // NOI18N
        jPanel9.add(combo_search_reservation, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 290, 140, 30));

        txt_search_reservation.setFont(new java.awt.Font("Serif", 0, 14)); // NOI18N
        txt_search_reservation.setSelectionColor(new java.awt.Color(0, 153, 153));
        txt_search_reservation.addCaretListener(new javax.swing.event.CaretListener() {
            public void caretUpdate(javax.swing.event.CaretEvent evt) {
                txt_search_reservationCaretUpdate(evt);
            }
        });
        jPanel9.add(txt_search_reservation, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 290, 270, 30));

        jLabel40.setFont(new java.awt.Font("Segoe UI Semibold", 0, 14)); // NOI18N
        jLabel40.setText("Search By");
        jPanel9.add(jLabel40, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 260, 140, 30));

        table_reservation.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "Rsv Id", "Guest Id", "Room Id", "check in", "check out", "Cost"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        table_reservation.setColorBackgoundHead(new java.awt.Color(0, 153, 153));
        table_reservation.setColorSelBackgound(new java.awt.Color(255, 51, 102));
        table_reservation.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        table_reservation.setRowHeight(30);
        table_reservation.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                table_reservationMouseClicked(evt);
            }
        });
        jScrollPane3.setViewportView(table_reservation);

        jPanel9.add(jScrollPane3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 330, 790, 270));

        jPanel9.add(combo_room_id, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 100, 200, 30));

        jPanel9.add(combo_guest_id, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 50, 200, 30));

        jLabel41.setFont(new java.awt.Font("Segoe UI Semibold", 0, 14)); // NOI18N
        jLabel41.setText("Cost");
        jPanel9.add(jLabel41, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 150, 100, 40));

        jLabel42.setFont(new java.awt.Font("Segoe UI Semibold", 0, 14)); // NOI18N
        jLabel42.setText("Check in");
        jPanel9.add(jLabel42, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 220, 100, 40));

        btn_get_cost.setText("Get Cost");
        btn_get_cost.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_get_costActionPerformed(evt);
            }
        });
        jPanel9.add(btn_get_cost, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 160, -1, 30));

        date_check_out.setColorBackground(new java.awt.Color(0, 153, 153));
        date_check_out.setColorButtonHover(new java.awt.Color(255, 153, 51));
        date_check_out.setColorForeground(new java.awt.Color(0, 153, 153));
        date_check_out.setPlaceholder("Check out Date");
        jPanel9.add(date_check_out, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 270, -1, -1));

        date_check_in.setColorBackground(new java.awt.Color(0, 153, 153));
        date_check_in.setColorButtonHover(new java.awt.Color(255, 153, 51));
        date_check_in.setColorForeground(new java.awt.Color(0, 153, 153));
        date_check_in.setPlaceholder("Check in Date");
        jPanel9.add(date_check_in, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 220, -1, -1));

        tab_reservations.add(jPanel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 10, 820, 610));

        jTabbedPane1.addTab("reservations", tab_reservations);

        tab_manage_users.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel10.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel35.setFont(new java.awt.Font("Segoe UI Semibold", 0, 14)); // NOI18N
        jLabel35.setText("Username");
        jPanel10.add(jLabel35, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 40, 100, 30));

        jLabel43.setFont(new java.awt.Font("Segoe UI Semibold", 0, 14)); // NOI18N
        jLabel43.setText("Email");
        jPanel10.add(jLabel43, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 130, 100, 50));

        jLabel44.setFont(new java.awt.Font("Segoe UI Semibold", 0, 14)); // NOI18N
        jLabel44.setText("Passwords");
        jPanel10.add(jLabel44, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 90, 100, 40));
        jPanel10.add(txt_user_phone, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 190, -1, -1));
        jPanel10.add(txt_user_email, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 140, -1, -1));
        jPanel10.add(txt_user_password, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 90, -1, -1));
        jPanel10.add(txt_username, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 40, -1, -1));

        jLabel45.setIcon(new javax.swing.ImageIcon("C:\\Users\\ALAMIA\\Desktop\\Software Project\\settings.png")); // NOI18N
        jPanel10.add(jLabel45, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 40, -1, -1));

        btn_insert_user.setBackground(new java.awt.Color(0, 153, 153));
        btn_insert_user.setText("Add");
        btn_insert_user.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_insert_userActionPerformed(evt);
            }
        });
        jPanel10.add(btn_insert_user, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 40, -1, -1));

        btn_update_user.setBackground(new java.awt.Color(0, 153, 153));
        btn_update_user.setText("Update");
        btn_update_user.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_update_userActionPerformed(evt);
            }
        });
        jPanel10.add(btn_update_user, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 110, -1, -1));

        jLabel46.setFont(new java.awt.Font("Segoe UI Semibold", 0, 14)); // NOI18N
        jLabel46.setText("Phone");
        jPanel10.add(jLabel46, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 180, 100, 40));

        btn_remove_user.setBackground(new java.awt.Color(0, 153, 153));
        btn_remove_user.setText("Remove");
        btn_remove_user.setColorHover(new java.awt.Color(255, 0, 0));
        btn_remove_user.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_remove_userActionPerformed(evt);
            }
        });
        jPanel10.add(btn_remove_user, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 180, -1, -1));

        combo_search_user.setBackground(new java.awt.Color(204, 204, 204));
        combo_search_user.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "ID", "Name" }));
        combo_search_user.setColorArrow(new java.awt.Color(0, 153, 153));
        combo_search_user.setColorBorde(new java.awt.Color(0, 153, 153));
        combo_search_user.setColorFondo(new java.awt.Color(0, 153, 153));
        combo_search_user.setFont(new java.awt.Font("Serif", 0, 18)); // NOI18N
        combo_search_user.setName("select"); // NOI18N
        jPanel10.add(combo_search_user, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 280, 100, 30));

        txt_search_user.setFont(new java.awt.Font("Serif", 0, 14)); // NOI18N
        txt_search_user.setSelectionColor(new java.awt.Color(0, 153, 153));
        txt_search_user.addCaretListener(new javax.swing.event.CaretListener() {
            public void caretUpdate(javax.swing.event.CaretEvent evt) {
                txt_search_userCaretUpdate(evt);
            }
        });
        jPanel10.add(txt_search_user, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 280, 310, 30));

        btn_clear_user.setBackground(new java.awt.Color(0, 153, 153));
        btn_clear_user.setText("Clear");
        btn_clear_user.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_clear_userActionPerformed(evt);
            }
        });
        jPanel10.add(btn_clear_user, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 180, -1, -1));

        jLabel47.setFont(new java.awt.Font("Segoe UI Semibold", 0, 14)); // NOI18N
        jLabel47.setText("Search By");
        jPanel10.add(jLabel47, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 280, 140, 30));

        table_user.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "User Id", "Username", "Password", "Email", "Phone"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        table_user.setColorBackgoundHead(new java.awt.Color(0, 153, 153));
        table_user.setColorSelBackgound(new java.awt.Color(255, 51, 102));
        table_user.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        table_user.setRowHeight(30);
        table_user.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                table_userMouseClicked(evt);
            }
        });
        jScrollPane4.setViewportView(table_user);

        jPanel10.add(jScrollPane4, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 330, 790, 270));

        tab_manage_users.add(jPanel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 10, 820, 610));

        jTabbedPane1.addTab("manage_users", tab_manage_users);

        getContentPane().add(jTabbedPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 0, 820, 650));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void label_dashboardMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_label_dashboardMouseClicked
        // TODO add your handling code here:
        jTabbedPane1.setSelectedIndex(0);
        Color dark = new Color(0, 102, 102);
        Color light = new Color(0, 153, 153);
        dashboard.setBackground(dark);
        guests.setBackground(light);
        rooms.setBackground(light);
        reservations.setBackground(light);
        manage_users.setBackground(light);
    }//GEN-LAST:event_label_dashboardMouseClicked

    private void jLabel14MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel14MouseClicked
        // TODO add your handling code here:
        jTabbedPane1.setSelectedIndex(1);
        Color dark = new Color(0, 102, 102);
        Color light = new Color(0, 153, 153);
        dashboard.setBackground(light);
        guests.setBackground(dark);
        rooms.setBackground(light);
        reservations.setBackground(light);
        manage_users.setBackground(light);
    }//GEN-LAST:event_jLabel14MouseClicked

    private void btn_logoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_logoutActionPerformed
        // TODO add your handling code here:
        Login login = new Login();
        login.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btn_logoutActionPerformed

    private void jLabel4MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel4MouseClicked
        // TODO add your handling code here:
        jTabbedPane1.setSelectedIndex(2);
        Color dark = new Color(0, 102, 102);
        Color light = new Color(0, 153, 153);
        dashboard.setBackground(light);
        guests.setBackground(light);
        rooms.setBackground(dark);
        reservations.setBackground(light);
        manage_users.setBackground(light);
    }//GEN-LAST:event_jLabel4MouseClicked

    private void jLabel5MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel5MouseClicked
        // TODO add your handling code here:
        jTabbedPane1.setSelectedIndex(3);
        Color dark = new Color(0, 102, 102);
        Color light = new Color(0, 153, 153);
        dashboard.setBackground(light);
        guests.setBackground(light);
        rooms.setBackground(light);
        reservations.setBackground(dark);
        manage_users.setBackground(light);
    }//GEN-LAST:event_jLabel5MouseClicked

    private void jLabel13MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel13MouseClicked
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_jLabel13MouseClicked

    private void jLabel33MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel33MouseClicked
        // TODO add your handling code here:
        jTabbedPane1.setSelectedIndex(4);
        Color dark = new Color(0, 102, 102);
        Color light = new Color(0, 153, 153);
        dashboard.setBackground(light);
        guests.setBackground(light);
        rooms.setBackground(light);
        reservations.setBackground(light);
        manage_users.setBackground(dark);
    }//GEN-LAST:event_jLabel33MouseClicked

    private void table_guestMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_table_guestMouseClicked
        // TODO add your handling code here:
        DefaultTableModel dft = (DefaultTableModel) table_guest.getModel();
        int selected_row = table_guest.getSelectedRow();

        txt_name.setText(dft.getValueAt(selected_row, 1).toString());
        txt_phone.setText(dft.getValueAt(selected_row, 2).toString());
        txt_email.setText(dft.getValueAt(selected_row, 3).toString());
        txt_city.setText(dft.getValueAt(selected_row, 4).toString());
        String gender = dft.getValueAt(selected_row, 5).toString();
        if (gender.equals("Male")) {
            radio_male.setSelected(true);
            //radio_male.doClick();
        } else {
            radio_female.setSelected(true);
            //radio_female.doClick();
        }
    }//GEN-LAST:event_table_guestMouseClicked

    private void btn_insert_guestActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_insert_guestActionPerformed
        try {
            // TODO add your handling code here:
            Guest guest = new Guest();
            guest.setName(txt_name.getText());
            guest.setPhoneNumber(txt_phone.getText());
            guest.setEmail(txt_email.getText());
            guest.setCity(txt_city.getText());
            guest.setGenderFromRadioButtons(radio_male, radio_female);
            guest.insertGuest(url, table_guest);
            Guest.update_guests_table(url, table_guest);
            Guest.count_nums(url, label_numGuests);

        } catch (SQLException ex) {
            Logger.getLogger(Home.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btn_insert_guestActionPerformed

    private void btn_update_guestActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_update_guestActionPerformed
        try {
            // TODO add your handling code here:

            Guest guest = new Guest(Guest.getSelectedRow(table_guest), txt_name.getText(), txt_phone.getText(), txt_email.getText(), txt_city.getText(), "");

            if (radio_male.isSelected()) {
                guest.setGender("Male");
            } else if (radio_female.isSelected()) {
                guest.setGender("Female");
            }

            guest.updateGuest(url, table_guest);
            Guest.update_guests_table(url, table_guest);
            Guest.clear_guest_information(txt_name, txt_phone, txt_email, txt_city, btnGroup_Guest);
        } catch (SQLException ex) {
            Logger.getLogger(Home.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btn_update_guestActionPerformed

    private void btn_remove_guestActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_remove_guestActionPerformed
        try {
            // TODO add your handling code here:
            Guest guest = new Guest();
            guest.setGuestID(Guest.getSelectedRow(table_guest));
            guest.deleteGuest(url, table_guest);
            Guest.update_guests_table(url, table_guest);
            Guest.count_nums(url, label_numGuests);
            Guest.clear_guest_information(txt_name, txt_phone, txt_email, txt_city, btnGroup_Guest);
        } catch (SQLException ex) {
            Logger.getLogger(Home.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btn_remove_guestActionPerformed

    private void txt_search_guestCaretUpdate(javax.swing.event.CaretEvent evt) {//GEN-FIRST:event_txt_search_guestCaretUpdate
        // TODO add your handling code here:
        Guest.search(url, combo_search_guest, txt_search_guest, table_guest);
    }//GEN-LAST:event_txt_search_guestCaretUpdate

    private void btn_clear_guestActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_clear_guestActionPerformed
        Guest.clear_guest_information(txt_name, txt_phone, txt_email, txt_city, btnGroup_Guest);
    }//GEN-LAST:event_btn_clear_guestActionPerformed

    private void btn_insert_roomActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_insert_roomActionPerformed

        try {
            Room room = new Room();
            room.setRoom_number(txt_room_number.getText());
            room.setBedrooms(Integer.parseInt(combo_bedrooms.getSelectedItem().toString()));
            room.setRoom_type(combo_room_type.getSelectedItem().toString());
            room.setPrice(Double.parseDouble(txt_price.getText()));
            room.setStatusFromRadioButtons(radio_free, radio_booked);
            room.insertRoom(url, table_room);
            Room.update_rooms_table(url, table_room);
            Room.count_free_rooms(url, label_booked);
            Room.count_booked_rooms(url, label_free);
            combo_room_id.removeAllItems();
            Reservation.getRooms(url, combo_room_id);
        } catch (SQLException ex) {
            Logger.getLogger(Home.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btn_insert_roomActionPerformed

    private void btn_update_roomActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_update_roomActionPerformed
        try {
            // TODO add your handling code here:
            Room room = new Room();
            room.setRoomID(Room.getSelectedRow(table_room));
            room.setRoom_number(txt_room_number.getText());
            room.setBedrooms(Integer.parseInt(combo_bedrooms.getSelectedItem().toString()));
            room.setRoom_type(combo_room_type.getSelectedItem().toString());
            room.setRoom_number(txt_room_number.getText());
            room.setPrice(Double.parseDouble(txt_price.getText()));
            room.setStatusFromRadioButtons(radio_free, radio_booked);
            room.updateRoom(url, table_room);
            Room.update_rooms_table(url, table_room);
            Room.clear_room_information(txt_room_number, combo_bedrooms, combo_room_type, txt_price, btnGroup_Room);
        } catch (SQLException ex) {
            Logger.getLogger(Home.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btn_update_roomActionPerformed

    private void btn_remove_roomActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_remove_roomActionPerformed
        try {
            // TODO add your handling code here:
            Room room = new Room();
            room.setRoomID(Room.getSelectedRow(table_room));
            room.deleteRoom(url, table_room);
            Room.update_rooms_table(url, table_room);
            Room.count_free_rooms(url, label_booked);
            Room.count_booked_rooms(url, label_free);
            combo_room_id.removeAllItems();
            Reservation.getRooms(url, combo_room_id);
            Room.clear_room_information(txt_room_number, combo_bedrooms, combo_room_type, txt_price, btnGroup_Room);
        } catch (SQLException ex) {
            Logger.getLogger(Home.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btn_remove_roomActionPerformed

    private void btn_refreshActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_refreshActionPerformed
        Room.update_rooms_table(url, table_room);
    }//GEN-LAST:event_btn_refreshActionPerformed

    private void table_roomMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_table_roomMouseClicked
        // TODO add your handling code here:
        DefaultTableModel dft = (DefaultTableModel) table_room.getModel();
        int selected_row = table_room.getSelectedRow();

        txt_room_number.setText(dft.getValueAt(selected_row, 1).toString());
        combo_bedrooms.setSelectedItem(dft.getValueAt(selected_row, 2).toString());
        combo_room_type.setSelectedItem(dft.getValueAt(selected_row, 3).toString());
        txt_price.setText(dft.getValueAt(selected_row, 5).toString());
        String gender = dft.getValueAt(selected_row, 4).toString();
        if (gender.equals("Free")) {
            radio_free.setSelected(true);
            //radio_male.doClick();
        } else {
            radio_booked.setSelected(true);
            //radio_female.doClick();
        }
    }//GEN-LAST:event_table_roomMouseClicked

    private void btn_insert_userActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_insert_userActionPerformed
        // TODO add your handling code here:
        try {
            // TODO add your handling code here:
            User user = new User();
            user.setName(txt_username.getText());
            user.setPhoneNumber(txt_user_phone.getText());
            user.setEmail(txt_user_email.getText());
            user.setPassword(txt_user_password.getText());
            user.insertUser(url, table_user);
            User.update_users_table(url, table_user);
        } catch (SQLException ex) {
            Logger.getLogger(Home.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btn_insert_userActionPerformed

    private void btn_update_userActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_update_userActionPerformed

        try {
            // TODO add your handling code here:

            User user = new User(User.getSelectedRow(table_user), txt_username.getText(), txt_user_phone.getText(), txt_user_email.getText(), txt_user_password.getText());
            user.updateUser(url, table_user);
            User.update_users_table(url, table_user);
            User.clear_user_information(txt_username, txt_user_phone, txt_user_email, txt_user_password);
        } catch (SQLException ex) {
            Logger.getLogger(Home.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btn_update_userActionPerformed

    private void btn_remove_userActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_remove_userActionPerformed
        try {

            // TODO add your handling code here:
            User user = new User();
            user.setUserID(User.getSelectedRow(table_user));
            user.deleteUser(url, table_user);
            User.update_users_table(url, table_user);
            User.clear_user_information(txt_username, txt_user_phone, txt_user_email, txt_user_password);
        } catch (SQLException ex) {
            Logger.getLogger(Home.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btn_remove_userActionPerformed

    private void txt_search_userCaretUpdate(javax.swing.event.CaretEvent evt) {//GEN-FIRST:event_txt_search_userCaretUpdate
        // TODO add your handling code here:
        User.search(url, combo_search_user, txt_search_user, table_user);
    }//GEN-LAST:event_txt_search_userCaretUpdate

    private void btn_clear_userActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_clear_userActionPerformed
        // TODO add your handling code here:
        User.clear_user_information(txt_username, txt_user_phone, txt_user_email, txt_user_password);

    }//GEN-LAST:event_btn_clear_userActionPerformed

    private void table_userMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_table_userMouseClicked
        // TODO add your handling code here:
        DefaultTableModel dft = (DefaultTableModel) table_user.getModel();
        int selected_row = table_user.getSelectedRow();

        txt_username.setText(dft.getValueAt(selected_row, 1).toString());
        txt_user_password.setText(dft.getValueAt(selected_row, 2).toString());
        txt_user_email.setText(dft.getValueAt(selected_row, 3).toString());
        txt_user_phone.setText(dft.getValueAt(selected_row, 4).toString());


    }//GEN-LAST:event_table_userMouseClicked

    private void btn_get_costActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_get_costActionPerformed
        try {
            // TODO add your handling code here:
            Reservation.getCost(url, combo_room_id, txt_cost, date_check_in, date_check_out);
        } catch (SQLException ex) {
            Logger.getLogger(Home.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btn_get_costActionPerformed

    private void table_reservationMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_table_reservationMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_table_reservationMouseClicked

    private void txt_search_reservationCaretUpdate(javax.swing.event.CaretEvent evt) {//GEN-FIRST:event_txt_search_reservationCaretUpdate
        // TODO add your handling code here:
        Reservation.search(url, combo_search_reservation, txt_search_reservation, table_reservation);
    }//GEN-LAST:event_txt_search_reservationCaretUpdate

    private void btn_remove_rsvActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_remove_rsvActionPerformed
        // TODO add your handling code here:
        try {
            // TODO add your handling code here:
            Reservation rsv = new Reservation();
           // Room room = new Room();
            rsv.setRsvID(Room.getSelectedRow(table_reservation));
            rsv.deleteReservation(url, table_reservation);
            Reservation.update_reservation_table(url, table_reservation);
            Room.update_rooms_table(url, table_room);
            Room.count_free_rooms(url, label_free);
            Room.count_booked_rooms(url, label_booked);
            Reservation.count_total_income(url, label_income);
            combo_room_id.removeAllItems();
            Reservation.getRooms(url, combo_room_id);
        } catch (SQLException ex) {
            Logger.getLogger(Home.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btn_remove_rsvActionPerformed

    private void btn_insert_rsvActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_insert_rsvActionPerformed
        try {
            // TODO add your handling code here:
            Date checkInDate = date_check_in.getDatoFecha();
            Date checkOutDate = date_check_out.getDatoFecha();

            // Format dates
            SimpleDateFormat sdf = new SimpleDateFormat("yyyy/MM/dd");
            String formattedCheckInDate = sdf.format(checkInDate);
            String formattedCheckOutDate = sdf.format(checkOutDate);
            Reservation rsv = new Reservation();
            rsv.setGuest_id(combo_guest_id.getSelectedItem().toString());
            rsv.setRoom_id(combo_room_id.getSelectedItem().toString());
            rsv.setCheck_in_date(formattedCheckInDate);
            rsv.setCheck_out_date(formattedCheckOutDate);
            rsv.setTotal_cost(Double.parseDouble(txt_cost.getText()));
            rsv.insertReservation(url, table_reservation);
            Reservation.update_reservation_table(url, table_reservation);
            Reservation.roomStatusBooked(url, combo_room_id);
            Room.update_rooms_table(url, table_room);
            Room.count_booked_rooms(url, label_booked);
            Room.count_free_rooms(url, label_free);
            Reservation.count_total_income(url, label_income);
            combo_room_id.removeAllItems();
            Reservation.getRooms(url, combo_room_id);
        } catch (SQLException ex) {
            Logger.getLogger(Home.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btn_insert_rsvActionPerformed

    private void combo_search_statusItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_combo_search_statusItemStateChanged
        // TODO add your handling code here:
        Room.status_search(url, combo_search_status, table_room);
    }//GEN-LAST:event_combo_search_statusItemStateChanged

    private void btn_clear3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_clear3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btn_clear3ActionPerformed

    private void combo_search_typeItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_combo_search_typeItemStateChanged
        // TODO add your handling code here:
        Room.room_type_search(url, combo_search_type, table_room);
    }//GEN-LAST:event_combo_search_typeItemStateChanged

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>


        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Home().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup btnGroup_Guest;
    private javax.swing.ButtonGroup btnGroup_Room;
    private rojeru_san.complementos.RSButtonHover btn_clear3;
    private rojeru_san.complementos.RSButtonHover btn_clear_guest;
    private rojeru_san.complementos.RSButtonHover btn_clear_user;
    private javax.swing.JButton btn_get_cost;
    private rojeru_san.complementos.RSButtonHover btn_insert_guest;
    private rojeru_san.complementos.RSButtonHover btn_insert_room;
    private rojeru_san.complementos.RSButtonHover btn_insert_rsv;
    private rojeru_san.complementos.RSButtonHover btn_insert_user;
    private rojeru_san.complementos.RSButtonHover btn_logout;
    private rojeru_san.complementos.RSButtonHover btn_refresh;
    private rojeru_san.complementos.RSButtonHover btn_remove_guest;
    private rojeru_san.complementos.RSButtonHover btn_remove_room;
    private rojeru_san.complementos.RSButtonHover btn_remove_rsv;
    private rojeru_san.complementos.RSButtonHover btn_remove_user;
    private rojeru_san.complementos.RSButtonHover btn_update_guest;
    private rojeru_san.complementos.RSButtonHover btn_update_room;
    private rojeru_san.complementos.RSButtonHover btn_update_user;
    private javax.swing.JComboBox<String> combo_bedrooms;
    private javax.swing.JComboBox<String> combo_guest_id;
    private javax.swing.JComboBox<String> combo_room_id;
    private javax.swing.JComboBox<String> combo_room_type;
    private rojerusan.RSComboMetro combo_search_guest;
    private rojerusan.RSComboMetro combo_search_reservation;
    private rojerusan.RSComboMetro combo_search_status;
    private rojerusan.RSComboMetro combo_search_type;
    private rojerusan.RSComboMetro combo_search_user;
    private javax.swing.JPanel dashboard;
    private rojeru_san.componentes.RSDateChooser date_check_in;
    private rojeru_san.componentes.RSDateChooser date_check_out;
    private javax.swing.JPanel guests;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JLabel jLabel31;
    private javax.swing.JLabel jLabel32;
    private javax.swing.JLabel jLabel33;
    private javax.swing.JLabel jLabel35;
    private javax.swing.JLabel jLabel36;
    private javax.swing.JLabel jLabel37;
    private javax.swing.JLabel jLabel38;
    private javax.swing.JLabel jLabel39;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel40;
    private javax.swing.JLabel jLabel41;
    private javax.swing.JLabel jLabel42;
    private javax.swing.JLabel jLabel43;
    private javax.swing.JLabel jLabel44;
    private javax.swing.JLabel jLabel45;
    private javax.swing.JLabel jLabel46;
    private javax.swing.JLabel jLabel47;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel10;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JLabel label_booked;
    private javax.swing.JLabel label_dashboard;
    private javax.swing.JLabel label_free;
    private javax.swing.JLabel label_income;
    private javax.swing.JLabel label_numGuests;
    private javax.swing.JPanel manage_users;
    private javax.swing.JRadioButton radio_booked;
    private javax.swing.JRadioButton radio_female;
    private javax.swing.JRadioButton radio_free;
    private javax.swing.JRadioButton radio_male;
    private javax.swing.JPanel reservations;
    private javax.swing.JPanel rooms;
    private javax.swing.JPanel tab_dashboard;
    private javax.swing.JPanel tab_guests;
    private javax.swing.JPanel tab_manage_users;
    private javax.swing.JPanel tab_reservations;
    private javax.swing.JPanel tab_rooms;
    private rojeru_san.complementos.RSTableMetro table_guest;
    private rojeru_san.complementos.RSTableMetro table_reservation;
    private rojeru_san.complementos.RSTableMetro table_room;
    private rojeru_san.complementos.RSTableMetro table_user;
    private app.bolivia.swing.JCTextField txt_city;
    private app.bolivia.swing.JCTextField txt_cost;
    private app.bolivia.swing.JCTextField txt_email;
    private app.bolivia.swing.JCTextField txt_name;
    private app.bolivia.swing.JCTextField txt_phone;
    private app.bolivia.swing.JCTextField txt_price;
    private app.bolivia.swing.JCTextField txt_room_number;
    private javax.swing.JTextField txt_search_guest;
    private javax.swing.JTextField txt_search_reservation;
    private javax.swing.JTextField txt_search_user;
    private app.bolivia.swing.JCTextField txt_user_email;
    private app.bolivia.swing.JCTextField txt_user_password;
    private app.bolivia.swing.JCTextField txt_user_phone;
    private app.bolivia.swing.JCTextField txt_username;
    // End of variables declaration//GEN-END:variables

    public JPanel getManage_users() {
        return manage_users;
    }
}
